### ISSUE TITLE
Northwest Research

### ISSUE THREAD

**Issue by eeash** [VERSO-UVM/Wastewater-Infrastructure-Mapping#103]
- Visit the Northwest regional planning commission [website](https://www.nrpcvt.com/)
- Go through all the town websites and try to find any maps or data they may have about wastewater
- If you find any relevant maps or data, add them to the Datasets/Maps tab of our [shared spreadsheet](https://docs.google.com/spreadsheets/d/1SDGSDfk-hVn8zVeRq5xfMAiMoToIruGfTlXEfMV29p8/edit?usp=sharing)

**Comment by LouiseVaill** [comment]
Need to contact some town clerks.
