### ISSUE TITLE
Set up sync with WIM Team

### ISSUE THREAD

**Issue by kefortney** [VERSO-UVM/Wastewater-Infrastructure-Mapping#11]
Connect to the team lead and set up a meeting to introduce yourselves as the Business Consultant, Community Specialist and Technical Consultant.

In that meeting cover:

- Who are the primary users
- Who would be the potential contributors to the project
- What is needed to onboard potential contributors (readme, contributing doc)
- What technical hurdles are they facing
- How can they tell the the story of their project
- How would they measure the successful use of the project (i.e. downloads, research outputs, engagement)
- What researchers at UVM are exploring related areas

Please add or expand as need and walk out with 2-5 task for each of you. Add those tasks to the correct projects and assign them to yourself.

**Comment by henrikvtcodes** [comment]
when2meet: https://www.when2meet.com/?25218224-ZiLuk
