### ISSUE TITLE
Set up Sprint Planning Meeting

### ISSUE THREAD

**Issue by kefortney** [VERSO-UVM/Wastewater-Infrastructure-Mapping#2]
A sprint planning meeting is an event that establishes the product development goal and plan for the upcoming sprint, based on the team’s review of its product backlog.

A successful session will yield two important strategic items:

- The sprint goal: A short written summary of what the team plans to accomplish in the next sprint and put it in the team slack channel 
- The sprint backlog: Assigning issues to the next iteration for the upcoming sprint
- New Issues: Add or review any new issues needed for this or the next two sprints.

This reoccurring meeting every two weeks should be held the week before the sprint and should include the whole team. Add VERSO Director as Optional
This meeting should be recorded

**Comment by emmaspett** [comment]
Hi everyone! Please invite me to this :) emma.spett@uvm.edu
